version: "3.8"

services:
  mysqldb:
    image: arm64v8/mysql:oracle
    command: [ "--default-authentication-plugin=mysql_native_password" ]
    restart: "no"
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
      - MYSQL_USER=$MYSQLDB_USER_SA
      - MYSQL_PASSWORD=$MYSQLDB_SA_PASSWORD
      - MYSQL_ROOT_HOST=%
      - MYSQL_$MYSQLDB_USER_SA_HOST='%'
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - db:/var/lib/mysql
    networks:
      - calc_net

  app:
    depends_on:
      - mysqldb
    build: .
    volumes:
      - .:/opt
    restart: "no"
    env_file: ./.env
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url": "jdbc:mysql://mysqldb:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE?useSSL=false",
        "spring.datasource.username": "$MYSQLDB_USER_SA",
        "spring.datasource.password": "$MYSQLDB_SA_PASSWORD",
        "spring.jpa.properties.hibernate.dialect": "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto": "update"
      }'
    stdin_open: true
    tty: true
    networks:
      - calc_net

volumes:
  db:

networks:
  calc_net:
    name: calc_net